###############################################################################
#
# Makefile for a script (e.g. Python) JackCompiler project
#
# Students:
# Aya Jbara, ID 209048156, aya.jbara@mail.huji.ac.il 
# Joshua Herskowitz, ID 321658379, jherskow@cs.huji.ac.il
###############################################################################
all:
	chmod a+x JackCompiler
	
